name: Check Commit Message
on: [push]
jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        run: |
          if git log -1 --pretty=format:%s | grep -q "hello"; then
            echo "Commit message includes 'hello', stopping push..."
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
          fi
